## titlebar for weewx skins
## Copyright Tom Keffer, Matthew Wall
## See LICENSE.txt for your rights
## Edited by Miroslav Lach (miroslav.lach@tum.de) for the CoSESWeather-Project
#errorCatcher Echo

<div id="title_bar">
  <div id="tum_logo"><a href="index.html"><img src="tum_logo.png" alt="TUM Logo" width="85" height="45"></a></div>
  <div id="logo"><a href="index.html"><img src="icon_web.png" alt="COSESWeather Logo" width="100" height="65"></a></div>
  <div id="title">
    <h1 class="page_title">CoSES Weather-Station</h1> <p class="lastupdate">MSE, Garching Forschungszentrum</p>
    <p class="lastupdate">Last update: $current.dateTime</p>
  </div>
</div>
